# Generated by Django 5.1.6 on 2025-02-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahcine_reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=50)),
                ('shelf', models.CharField(max_length=50)),
                ('MRC', models.CharField(max_length=50)),
            ],
        ),
    ]
