# Generated by Django 5.1.6 on 2025-02-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_reception_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahcine_reception',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mahcine_reception',
            name='shelf',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mahcine_reception',
            name='technician_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
