# Generated by Django 5.1.6 on 2025-02-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_reception_app', '0002_alter_mahcine_reception_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahcine_reception',
            old_name='id',
            new_name='Ids',
        ),
    ]
