# Generated by Django 5.1.6 on 2025-02-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Machine_reception_app', '0003_rename_id_mahcine_reception_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahcine_reception',
            old_name='Ids',
            new_name='MN',
        ),
    ]
